spring:
  config:
    import:
      - nacos:user-service-dev-sql-config.yaml?refreshEnabled=true  # 从 Nacos 获取配置文件，并启用刷新功能
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848  # Nacos 服务器地址
      config:
        namespace: 8648100a-894e-469e-b4b7-0b191a94a21d  # 命名空间
        group: DEFAULT_GROUP  # 配置分组
        file-extension: yaml  # 配置文件扩展名

knowledge:
  jwt:
    secret: rwwr5d0a6c8f18db7b913f2b5c6d25c6
    # JWT 密钥
    expiration: 604800  # JWT 过期时间，单位秒，默认 7 天
