server:
  port: 8083

spring:
  config:
    import:
      - nacos:file-service-dev-sql-config.yaml?refreshEnabled=true  # 从 Nacos 获取配置文件，并启用刷新功能
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848  # Nacos 服务器地址
      config:
        namespace: 8648100a-894e-469e-b4b7-0b191a94a21d  # 命名空间
        group: DEFAULT_GROUP  # 配置分组
        file-extension: yaml  # 配置文件扩展名

# elasticsearch配置
elasticsearch:
  # elasticsearch配置
  #自己的账号名
  userName: elastic
  #自己的密码
  password: w250927
  # 自定义属性---设置是否开启ES,false表不开窍ES
  open: true
  # es集群名称,如果下载es设置了集群名称,则使用配置的集群名称
  clusterName: es
  hosts: 127.0.0.1:9200
  # es 请求方式
  scheme: https
  # es 连接超时时间
  connectTimeOut: 1000
  # es socket 连接超时时间
  socketTimeOut: 30000
  # es 请求超时时间
  connectionRequestTimeOut: 500
  # es 最大连接数
  maxConnectNum: 100
  # es 每个路由的最大连接数
  maxConnectNumPerRoute: 100
